### ISSUE TITLE
- (void)awakeFromNib missing

### ISSUE THREAD

**Issue by SimonJakubowski** [steipete/PSPDFTextView#15]
if loaded from nib, the initWithFrame method will not get called

**Comment by steipete** [comment]
Ah, I never use Interface builder. Can you send a PR? Thanks!

**Comment by fillito** [comment]
@SimonJakubowski  I also needed this and already submitted a pull request https://github.com/steipete/PSPDFTextView/pull/16

**Comment by yas375** [comment]
Looks like this issue can be now closed.
