### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by kornifex** [steipete/PSPDFTextView#6]
Hello,

I can't seem to find PSPDFTextView on Cocoapods… 
Am I missing something?

Thanks!

**Comment by steipete** [comment]
It's only local for now.

**Comment by trivektor** [comment]
This library looks pretty cool. Please consider uploading it to CocoaPods. Thanks.

**Comment by ruddfawcett** [comment]
@trivektor if you fork it and add a pod, you can link to the repo in your Podfile.

**Comment by trivektor** [comment]
@rexfinn Nice suggestion. I'm still new to CocoaPods after all. Thanks.
